server.port=${PORT:8080}
spring.application.name=fitprep

# PostgreSQL — Supabase (Usamos los nombres de variables estándar de Render/Spring)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.jucxdoqjxzoezxrvmrlf.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Bravo160697182560}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate & SSL Obligatorio para Supabase
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Fuerza a que la conexión use SSL (Crucial para entornos en la nube)
spring.datasource.properties.sslmode=require

# Flyway — desactivado porque ya corrimos las migraciones manualmente
spring.flyway.enabled=false